const express=require('express'),cheerio=require('cheerio'),path=require('path');
const app=express();app.use(express.json());app.use(express.static(__dirname));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const clean=s=>(s||'').replace(/\s+/g,' ').trim();
function abs(base,h){try{return new URL(h,base).href.split('#')[0]}catch{return null}}
function same(a,b){try{return new URL(a).origin===new URL(b).origin}catch{return false}}
function noise(u){try{let x=new URL(u),p=x.pathname.toLowerCase();return !same(u,ORIGIN)||/\.(jpg|jpeg|png|gif|webp|svg|css|js|pdf|zip)$/i.test(p)||/\/(cart|checkout|login|account|wishlist|search|contact)\b/.test(p)}catch{return true}}
let ORIGIN='https://tienda.goflymx.com';
async function get(url){let r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 GoFlyMX-Stock-Request/1.0','accept':'text/html,application/xhtml+xml'}});if(!r.ok)throw Error('HTTP '+r.status);return r.text()}
function code($){for(let s of ['[itemprop="sku"]','.sku','.product-sku','.product-code','.reference','[class*="sku"]']){let e=$(s).first();if(e.length){let t=clean(e.attr('content')||e.text());if(t)return t}}let b=clean($('body').text()),m=b.match(/(?:c[oó]digo|sku|ref(?:erencia)?|art[ií]culo)\s*[:#-]?\s*([A-Z0-9][A-Z0-9._\/-]{1,70})/i);return m?clean(m[1]):''}
function stock($){let b=clean($('body').text());if(/\bSIN\s+STOCK\b/i.test(b)||/\bPRODUCTO\s+NO\s+DISPONIBLE\b/i.test(b)||/\bNO\s+DISPONIBLE\b/i.test(b))return {n:1,label:'1 (SIN STOCK)',sinStock:true};for(let s of ['[itemprop="inventoryLevel"]','.stock','.product-stock','.availability','.stock-status','.inventory']){let e=$(s).first();if(e.length){let t=clean(e.attr('content')||e.attr('data-stock')||e.text()),m=t.match(/(?:^|\D)(\d+)(?:\D|$)/);if(m){let n=+m[1];return {n,label:String(n),sinStock:n===0}}}}let ps=[/(?:stock|existencia|disponibilidad)\s*(?:real)?\s*[:=-]?\s*(\d+)/i,/(\d+)\s*(?:unidades?|uds?)\s*(?:en\s+)?(?:stock|existencia)/i];for(let p of ps){let m=b.match(p);if(m){let n=+m[1];return {n,label:String(n),sinStock:n===0}}}return {n:null,label:'NO DETECTADO',sinStock:false}}
function links(html,url){let $=cheerio.load(html),a=new Set();$('a[href]').each((_,e)=>{let u=abs(url,$(e).attr('href'));if(u&&!noise(u))a.add(u)});return [...a]}
function products(html,url){let $=cheerio.load(html),a=new Set();$('a[href]').each((_,e)=>{let u=abs(url,$(e).attr('href'));if(u&&same(u,ORIGIN)&&/\.html(?:\?|$)/i.test(new URL(u).pathname))a.add(u)});return [...a]}
app.post('/api/stock',async(req,res)=>{ORIGIN=String(req.body.origin||'https://tienda.goflymx.com').replace(/\/+$/,'');let max=Math.min(+req.body.maxPages||1000,10000),con=Math.min(Math.max(+req.body.concurrency||3,1),8);res.setHeader('Content-Type','application/x-ndjson');let send=x=>res.write(JSON.stringify(x)+'\n');try{let q=[ORIGIN+'/'],seen=new Set(),prods=new Set(),pages=0,errors=0;while(q.length&&pages<max){let batch=[];while(q.length&&batch.length<con&&pages+batch.length<max){let u=q.shift();if(!seen.has(u)){seen.add(u);batch.push(u)}}let rs=await Promise.all(batch.map(async u=>{try{return{u,h:await get(u)}}catch(e){return{u,e}}}));for(let r of rs){pages++;if(r.e){errors++;continue}for(let p of products(r.h,r.u))prods.add(p);for(let u of links(r.h,r.u))if(!seen.has(u)&&q.length<max*2)q.push(u)}send({type:'progress',percent:Math.min(50,Math.round(pages/max*50)),message:`Descubriendo fichas: ${prods.size}`});await sleep(150)}let list=[...prods],done=0;for(let i=0;i<list.length;i+=con){let rs=await Promise.all(list.slice(i,i+con).map(async u=>{try{return{u,h:await get(u)}}catch(e){return{u,e}}}));for(let r of rs){done++;if(r.e)continue;let $=cheerio.load(r.h),c=code($),st=stock($);if(c&&st.n!==null&&st.n<2)send({type:'product',data:{codigo:c,stock:st.label,sinStock:st.sinStock}})}send({type:'progress',percent:50+Math.round(done/list.length*50),message:`REQUEST de stock: ${done}/${list.length}`});await sleep(150)}send({type:'done',message:`Finalizado. Solo se devolvieron códigos con stock < 2. SIN STOCK = 1. Fichas consultadas: ${done}.`});res.end()}catch(e){send({type:'done',message:'Error: '+e.message});res.end()}});
app.listen(3000,()=>console.log('http://localhost:3000'));
